INSERT INTO ROOMS VALUES(1,500,2,'AC','AVAILABLE',SYSDATE);
INSERT INTO ROOMS VALUES(2,500,2,'AVAILABLE','N/AC',SYSDATE);


CREATE OR REPLACE PROCEDURE ROOM_VALUES
(ROOM_PRICE IN NUMBER,ROOM_BEDS IN NUMBER, ROOM_TYPE VARCHAR, ROOM_STATUS VARCHAR)
IS
ROOM_NO NUMBER(5);
BEGIN
    SELECT MAX(ROOM_NUMBER)+1 INTO ROOM_NO FROM ROOMS;
    INSERT INTO ROOMS VALUES(ROOM_NO,ROOM_PRICE,ROOM_BEDS,ROOM_TYPE,ROOM_STATUS,SYSDATE);
END;
/

EXEC ROOM_VALUES(1000,4,'AC','NOT_AVAILABLE');

TRUNCATE ROOMS;

SELECT * FROM ROOMS;
