--ADDED THE PRIMARY KEY TO EACH TABLE ROOM CUSTOMER AND RECEPTION
select * from tab;

ALTER TABLE ROOMS
ADD PRIMARY KEY (ROOM_NUMBER);

DESC ROOMS; 

ALTER TABLE CUSTOMER
ADD PRIMARY KEY (CID);

DESC CUSTOMER; 

ALTER TABLE  RECEPTION
ADD PRIMARY KEY (RID);

DESC RECEPTION; 


ALTER TABLE CUSTOMER
ADD ROOM_DAYS NUMBER(3);

SELECT * FROM CUSTOMER;

-- NOW ADDING THE CONNECTION BETWEEN TABLES USING  FOREGIN KEY