CREATE TABLE ROOMS
(
    ROOM_NUMBER NUMBER(5),
    ROOM_PRICE NUMBER(10,2) NOT NULL,
    ROOM_BEDS NUMBER(5) NOT NULL,
    ROOM_TYPE VARCHAR(50) NOT NULL,
    ROOM_STATUS VARCHAR(50) NOT NULL,
    ROOM_AVAILBILITY DATE
);

CREATE TABLE CUSTOMER
(
    CID NUMBER(5),
    CNAME VARCHAR(20),
    CNUMBER NUMBER(5),
    ROOM_NUMBER NUMBER(10)
);

CREATE TABLE RECEPTION
(
    RID NUMBER(5),
    CID NUMBER(5),
    ROOM_NUMBER NUMBER(5)
);